using UnityEngine;


public class Tile : MonoBehaviour
{
    public const float stepHeight = 0.25f;
    
    public Point pos;
    public int height;

    public Vector3 center
    {
        get
        {
            return new Vector3(pos.x, height * stepHeight, pos.y);
        }
    }

    void Match()
    {
        transform.localPosition = new Vector3(pos.x, height * stepHeight / 2f, pos.y);
        transform.localScale = new Vector3(1f, height * stepHeight, 1f);
    }
    public void Grow ()
    {
        height += 1;
        Match();
    }
    public void Shrink ()
    {
        height -= 1;
        Match();
    }
    public void Load(Point p, int h)
    {
        pos = p;
        height = h;
        Match();
    }
    public void Load(Vector3 v)
    {
        Load(new Point((int)v.x, (int)v.z), (int)v.y);
    }

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
